name: Build Singularity SIF

on:
  workflow_dispatch:  # Esecuzione manuale dal pannello GitHub
  push:
    paths:
      - 'cont.def'    # Esegui anche quando il file di definizione viene modificato

jobs:
  build-sif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Apptainer installation
        uses: actions/cache@v3
        id: apptainer-cache
        with:
          path: /usr/local/bin/apptainer
          key: apptainer-1.1.9

      - name: Install dependencies
        if: steps.apptainer-cache.outputs.cache-hit != 'true'
        run: |
          echo "Installazione delle dipendenze per Apptainer..."
          sudo apt-get update
          sudo apt-get install -y build-essential libseccomp-dev pkg-config squashfs-tools cryptsetup curl libfuse2 squashfuse fuse2fs

          # Installazione di Apptainer
          export VERSION=1.1.9
          echo "Scaricamento di Apptainer ${VERSION}..."
          wget https://github.com/apptainer/apptainer/releases/download/v${VERSION}/apptainer_${VERSION}_amd64.deb
          sudo dpkg -i apptainer_${VERSION}_amd64.deb
          rm apptainer_${VERSION}_amd64.deb

      - name: Verifica installazione Apptainer
        run: |
          apptainer version
          echo "Apptainer installato correttamente"

      - name: Verifica file di definizione
        run: |
          if [ ! -f "cont.def" ]; then
            echo "Errore: File di definizione cont.def non trovato"
            exit 1
          fi
          echo "File di definizione trovato, procedo con il build"
          cat cont.def

      - name: Build SIF from definition file
        run: |
          mkdir -p sif_build
          echo "Avvio build del container Singularity..."
          apptainer build --fakeroot sif_build/portrait_segmentation.sif cont.def
          echo "Build completato con successo"
          ls -lah sif_build/

      - name: Test container
        run: |
          echo "Test del container creato..."
          apptainer exec sif_build/portrait_segmentation.sif echo "Container funzionante!"

      - name: Upload SIF artifact
        uses: actions/upload-artifact@v3
        with:
          name: portrait_segmentation_sif
          path: sif_build/portrait_segmentation.sif
          if-no-files-found: error
          retention-days: 7